on:
  push:
    branches: [master, main]

jobs:

  dockerpush:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set env
      id: release
      run: echo ::set-output name=RELEASE_VERSION::$(git describe --match "[0-9]*.[0-9]*.[0-9]*" --tags $(git rev-list --tags --max-count=1))

    - 
      name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        registry: ghcr.io
        name: "ghcr.io/hazcod/sentinel2misp/sentinel2misp:${{ steps.vars.release.RELEASE_VERSION }}"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_semver: true
    - 
      name: Create GitHub release
      uses: actions/create-release@v1.1.4
      if: steps.release.outputs.RELEASE_VERSION != ''
      with:
          tag_name: ${{ steps.vars.outputs.alpine_version }}
          release_name: sentinel2misp
          draft: false
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}