on:
  push:
    branches: [master, main]

jobs:

  dockerpush:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    -
      uses: go-semantic-release/action@v1
      id: semantic
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      if: steps.semantic.outputs.version != ''
      with:
        registry: ghcr.io
        name: "ghcr.io/hazcod/sentinel2misp/sentinel2misp:${{ steps.semantic.outputs.version }}"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_semver: true
